### PR TITLE
fix: better checks of socket ready state

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by Supergiovane** [comment]
opssss... we're working on the same.
I'll check all toghether.

**Comment by robertsLando** [comment]
@Supergiovane I just sutmitted a fix, your last commit introduced an issue spotted by tests likely

**Comment by Supergiovane** [comment]
Yes, already done.

**Review by Supergiovane — DISMISSED** [review]

**Comment by robertsLando** [comment]
DPT tests are failing, now I have to do some other things but @mandrake-sw will take care of that

**Comment by robertsLando** [comment]
I have also enabled an eslint rule named `consistent-return` so errors like will be spotted by eslint now

**Comment by Supergiovane** [comment]
I'm fixing the conflicting code...

**Comment by robertsLando** [comment]
@Supergiovane why did you deleted the src/KNXClient.ts file?

**Review by Supergiovane — DISMISSED** [review]

**Pull request merged**
