### PR TITLE
fix: writeRaw broken with length <= 6bits

### LINKED ISSUE #23: writeRaw broken with length <= 6bits
**Salutation**
Hi there, thanks a lot for this wonderful piece of code ;-)

**Describe the bug**
short GroupValueWrite in writeRaw is not sent properly

**To Reproduce**
simply call 
knxUltimateClient.on(KNXClientEvents.connected, info => {
    // The client is connected
    console.log("Connected. On Duty", info);
    // WARNING, THIS WILL WRITE ON YOUR KNX BUS!
    knxUltimateClient.writeRaw("0/1/1", Buffer.from("05", "hex"), 3);
});

**Expected behavior**
should send a effective knx frame ending with value 0x83 , but sends .... 0x80

**Screenshots**

**Desktop (please complete the following information):**
 - OS: node

**Additional context**
A PR with the missing Math.ceil function to come now !!

### PR DESCRIPTION
**Pull request by RealByron**
Fixes #23

### CODE REVIEW

**Review by Supergiovane — APPROVED** [review]

**Comment by Supergiovane** [comment]
Hi
can you verify, please, this error in che CI / build 20.x check?

fix___23_writeRaw_broken_with_length____6bits_·_Supergiovane_KNXUltimate_c39e90a

**Comment by RealByron** [comment]
done !

**Comment by robertsLando** [comment]
@RealByron could you explain why Math.ceil is needed? is bitlength there a floating number?

**Comment by robertsLando** [comment]
@RealByron You just have to run `npm run lint-fix` in order to fix lint issues

**Comment by RealByron** [comment]
> @RealByron could you explain why Math.ceil is needed? is bitlength not an integer number?

since bitlength can be less than 8 you still have to allocate/copy one byte to uild the frame
Math.ceil ensure that it return 1 if bitLength is in the range [1, 8]

**Comment by RealByron** [comment]
should be ok now... I hope...  I pray for that

**Comment by robertsLando** [comment]
Oh ok yeah it's clear now I didn't see the `/8` at first sight :)

**Pull request merged**
